name: Android CI

on:
  push:
    branches:
      - '*'

jobs:
  build_debug:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Lint checks and tests
        run: ./gradlew --no-daemon --parallel clean lintFlossDebug testFlossDebug

      - name: Assemble Floss Debug
        run: ./gradlew assembleFlossDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: app-floss-debug.apk
          path: app/build/outputs/apk/floss/debug/app-floss-debug.apk
